### ISSUE TITLE
media-libs/waifu2x-converter-cpp build failure, reason unknown

### ISSUE THREAD

**Issue by q3cpma** [4re/vapoursynth-portage#106]
Hello I can't build either 5.3.3 or 9999 and I get this error:
```
/usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++ -DBUILD_TS=\"2021-12-14T17:07:27\" -DDEFAULT_MODELS_DIRECTORY=\"/usr/share/waifu2x-converter-cpp\" -DGIT_BRANCH=\"\" -DGIT_COMMIT_HASH=\"\" -DGIT_TAG=\"\" -DHAVE_OPENCV -DUNICODE -DX86OPT -D_UNICODE -Dw2xc_EXPORTS -I. -I/var/tmp/portage/media-libs/waifu2x-converter-cpp-5.3.3/work/waifu2x-converter-cpp-5.3.3/src -I/var/tmp/portage/media-libs/waifu2x-converter-cpp-5.3.3/work/waifu2x-converter-cpp-5.3.3/include -isystem /usr/include/opencv4  -O3 -march=native -pipe -std=gnu++17 -fPIC -MD -MT CMakeFiles/w2xc.dir/src/w2xconv.cpp.o -MF CMakeFiles/w2xc.dir/src/w2xconv.cpp.o.d -o CMakeFiles/w2xc.dir/src/w2xconv.cpp.o -c /var/tmp/portage/media-libs/waifu2x-converter-cpp-5.3.3/work/waifu2x-converter-cpp-5.3.3/src/w2xconv.cpp
In file included from /var/tmp/portage/media-libs/waifu2x-converter-cpp-5.3.3/work/waifu2x-converter-cpp-5.3.3/src/modelHandler.hpp:31,
                 from /var/tmp/portage/media-libs/waifu2x-converter-cpp-5.3.3/work/waifu2x-converter-cpp-5.3.3/src/w2xconv.cpp:35:
/var/tmp/portage/media-libs/waifu2x-converter-cpp-5.3.3/work/waifu2x-converter-cpp-5.3.3/include/picojson.h:197:63: error: macro "_serialize" passed 2 arguments, but takes just 0
  197 |   template <typename Iter> void _serialize(Iter os, int indent) const;
      |                                                               ^
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/x86gprintrin.h:71,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/immintrin.h:27,
                 from /usr/include/CL/cl_platform.h:487,
                 from /usr/include/CL/cl.h:21,
                 from /usr/include/CL/opencl.h:24,
                 from /var/tmp/portage/media-libs/waifu2x-converter-cpp-5.3.3/work/waifu2x-converter-cpp-5.3.3/src/CLlib.h:37,
                 from /var/tmp/portage/media-libs/waifu2x-converter-cpp-5.3.3/work/waifu2x-converter-cpp-5.3.3/src/Buffer.hpp:61,
                 from /var/tmp/portage/media-libs/waifu2x-converter-cpp-5.3.3/work/waifu2x-converter-cpp-5.3.3/src/w2xconv.cpp:34:
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/serializeintrin.h:37: note: macro "_serialize" defined here
   37 | #define _serialize()    __builtin_ia32_serialize ()
      |
```
which seems related to https://github.com/kazuho/picojson/issues/141. My problem is that I can't reproduce it when cloning and building, something with the Gentoo cmake config must be the cause (I suspect `-march=native` being what allows the inclusion of `immintrin.h`).

PS: I tried to recompile it because the current installed version I have failed to work with opencv-4.5.4, downgrading to 4.5.2 solved this problem.

**Comment by q3cpma** [comment]
Tell me if you need the complete build log and/or --info output.

**Comment by 4re** [comment]
This should be fixed now, make me know if it's not because it's basically untested.

**Comment by q3cpma** [comment]
On Thu, Dec 16, 2021 at 10:24:37AM -0800, 4re wrote:
> This should be fixed now, make me know if it's not because it's basically untested.
>

Thanks for the extensive patch, it does work now. For the OpenCV incompatibility,
rebuilding waifu2x-converter-cpp after the upgrade solved it (I was getting some
assertions, otherwise); depending on >=media-libs/opencv-3.3.0:= instead should do
the trick.
